### ISSUE TITLE
Introduce new parameter "failureAction" to specify the behaviour in error cases

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.hbase#101]
The operators HBaseDelete and HBasePut provide some error information on the optional output port for some error cases, but even these operators catch the **TableNotFoundException**.

We would need to introduce a new parameter "**failureAction**" to the operators:
Similar to the FileSink "writeFailureAction", we would need to introduce a parameter to specify the action when command fails.
This new parameter has "**failureAction**" should have values of log, terminate and errorAttribute.
- log is the current behaviour
- terminate will forward/throw exceptions that terminate the operator if no @catch annotation or ExceptionCatcher is in use.
- errorAttribute (requires an attribute on the output port, that will contain the error text)

**Comment by nmwaara** [comment]
This was created based off a customer support case, where they wish to utilize the ExceptionCatcher operator to catch the TableNotFoundException being thrown by the HBase operators. They had the following to say regarding this...

Our intension is to store failed messages some where for reprocess. In the current design of HBaseGet operator we do not have that option.
Give us guidance(alternate) to store those messages for reprocess.

Although (with the current toolkit implementation) they are able to see these TableNotFoundExceptions being reported in the stdouterr logs, they are not able to process this error in real time (with their applications) and reprocess their HBase call. Their goal is to be able to catch the exception with the ExceptionCatcher operator and then be able to reprocess their data as necessary from there.

**Comment by markheger** [comment]
I propose 2 stages:
first stage: Provide new parameter with 2 options: log and terminate
second stage: Add output port / output attribute and provide third option

**Comment by anouri** [comment]
After discussion with our developer team, we have decided to improve the HBASE toolkit with a new optional output port to all operators for error messages.
- It is compatible to older versions.
- The user can add an output port to get more information in case of any error.
- The error messages from Apache HBase will be forwarded to the SPL application.
- The following SPL sample shows the use of new output port.

         (stream<boolean success> HbasePut ; stream<rstring errorText> ErrorPort) = HBASEPut(inputStream)
         {
                param
                    tableName : "streamsSample_lotrrr" ;
                     rowAttrName : "character" ;
                     columnFamilyAttrName : "colF" ;
                     columnQualifierAttrName : "colQ" ;
                     valueAttrName : "value" ;
                     successAttr : "success" ;				
          }
          
          () as printErrors= Custom(ErrorPort)
          {
              logic 
                  onTuple ErrorPort : {printStringLn(" Error Message :  " + errorText);}				 
          }

And here is the output:

          Error Message : Table 'streamsSample_lotrrr' does not exists.

This error message is from Apache HBase exception handling.

**Comment by nmwaara** [comment]
I got an update from the customer with the following...

1. It is not just the “Table Not Found” exception, we just given you the simple exception case.
We want to catch all the exceptions that we get from HBase and Elasticsearch operators in our current  pipeline and want to reprocess (Ideally we need this for all the operators).

2. In this case we want to log the error and want to store the message in a specified file to reprocess.

3. The attributes that we needed are...
    a) LogFileName (with date and time) & LogFilePath - For logging exception (If we want to log exception in a different file)
    b) MessageAttributeName - Original Message to reprocess
    c) MessageStoreFileName - File name to store messages to reprocess
-----------
I'm not sure how feasible all of these improvements are necessarily, but I wanted to add them here for your review/discussion.

**Comment by anouri** [comment]
- The HBase toolkit returns all error messages that caused by HBase operators.
- The error messages have additional information like current date time and the name of operator that caused this error.
Example:

      20190215-100421 PutToTable:      Table 'streamsSample_lotrrr' does not exists.
      20190215-100421 GetFromTable:    Invalid Column name 

- It is possible to forward all error messages to a FileSink operator.
- It is possible to set the LogFilePath and the LogFileName in FileSink operator.
- The FileSink operator has possibility to create dynamic file names and writes messages to a log file.
   For example it can create daily a new file name like this : 
    /home/user1/logs/20190215-hbase-error-messages.log.

**Comment by anouri** [comment]
The error messages contains additional to the time stamp, operator name and error,  also the input tuple.
It helps the user to ﬁnd easily the root cause of errors.
Here is an example:

The input tuple has the following type:

       <rstring tableName, rstring character, rstring colF, rstring colQ, rstring value>

And the error message has these information:

       20190219-110421 PutToTable:      Table 'streamsSample_lotrrr' does not exists. ,TUPLE{streamsSample_lotrrr,Eowyn,appearance,overall,beautiful}

**Comment by anouri** [comment]
Correction delivered in version 3.4.0
https://github.com/IBMStreams/streamsx.hbase/releases/tag/v3.4.0

**Comment by anouri** [comment]
A sample with documentation has been provided in GitHub:
https://github.com/IBMStreams/streamsx.hbase/wiki/How-to-use-the-error-output-port-in-streamsx.hbase
