### ISSUE TITLE
Use the New successAttr

### ISSUE THREAD

**Issue by giuseppepastore88** [IBMStreams/streamsx.hbase#102]
Hi all,

how can I use the successAttr as the output of an HPut method?
Which values should the successAttr assume?
Can you provide an example?

We are trying to use it as in the following way, but always returns nothing:
		(stream<rstring successAttr> succAtt) as HBASE_PLC_close = HBASEPut(Kafka_AC_HBASE)
		{
			param
				rowAttrName : "key" ;
				valueAttrName : "json" ;
				tableName : "<table_schema.table_name>" ;
				staticColumnFamily : "cf1" ;
				hbaseSite : "<path_to_hbase>" ;
		}
		() as print = Custom(succAtt){
		logic onTuple succAtt:{
		printStringLn("succAtt: " + (rstring)succAtt);	
		} 

Thank you.

**Comment by anouri** [comment]
Hi @giuseppepastore88 

Here is an example:
How to use successAttr in HBASEPut operator.
Please use the latest release of HBASE toolkit.
https://github.com/IBMStreams/streamsx.hbase/releases/tag/v3.3.0

 		stream<boolean success> succAtt as HBASE_PLC_close = HBASEPut(Kafka_AC_HBASE)
		{
			param
				tableName : "your-table-table" ;
				rowAttrName : "key" ;
				columnFamilyAttrName : "colF" ;
				columnQualifierAttrName : "colQ" ;
				valueAttrName : "json" ;
				hbaseSite :  "path_to_hbase-site.xml";
				successAttr : "success" ;
		}

		() as print = Custom(succAtt)
		{
				logic
 				      onTuple succAtt : printStringLn("success : " + (rstring) success );
		}

**Comment by anouri** [comment]
Please check this document in GitHub.
It describes how to use successAttr in HBASEPut operator.
https://github.com/IBMStreams/streamsx.hbase/wiki/How-to-use-the-error-output-port-in-streamsx.hbase
