### ISSUE TITLE
The HBASEScan operator should support an input stream with none of these attributes: startRow, endRow and rowPrefix

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.hbase#107]
Since the HBASEScan operator supports then scan of the whole table if none of the parameters startRow, endRow and rowPrefix is applied the operator should probably also support an input stream with none of these attributes: startRow, endRow and rowPrefix.

**Comment by anouri** [comment]
The HBASEScan operator will support also with only one string as table name in input port.

**Comment by anouri** [comment]
Corrected

**Comment by anouri** [comment]
corrected in 

https://github.com/IBMStreams/streamsx.hbase/releases/tag/v3.6.0
