### ISSUE TITLE
HBASEScan Operator: inconsistent description and implementation

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.hbase#108]
The description of the HBASEScan operator says:
'If your specify only the **endRow** parameter, the table scan starts at the beginning and scans until the row specified in the **endRow** parameter.'

But in the implementation there is:
	@ContextCheck(compile = true)
	public static void checks(OperatorContextChecker checker) {
		checker.checkDependentParameters("endRow", "startRow");

Thus in fact, if the parameter 'endRow' is used also the 'startRow' parameter is required.

**Comment by anouri** [comment]
HBASEScan operator works now with the following parameters:
full sacn:                  It requires only **tableName**
scan with start row,  It requires **tableName** and **startRow**
scan with end row:   It requires **tableName** and **endRow**
scan with start and end row: It requires **tableName**, **startRow** and **endRow**  
The value of parameters can be supplied via input port tuples: 
The table name can be also supplied via input port. The value of **tableNameAttribute** parameter has to be set with the name of string in input port.

**Comment by anouri** [comment]
Corrected
