### ISSUE TITLE
Provide a Sample with Parameter tableNameAttribute

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.hbase#109]
We should supply a sample that demonstrates the usage of the parameter tableNameAttribute
and the probably the HBASEScan operator.

**Comment by anouri** [comment]
A SPL sample will provide to demonstrate the usage of the parameter tableNameAttribute for all HBASE operators.

**Comment by anouri** [comment]
A SPL sample is prepared.
It will be uploaded in wiki after the streamsx.hbase release.

**Comment by anouri** [comment]
A SPL sample has been provided:

This SPL sample application demonstrates
How to use the parameter **tableNameAttribute** in all HBASE operators.
How to delete rows from a HBASE table.
How to put data into a HBASE table.
How to scan rows from a HBASE table.

https://github.com/IBMStreams/streamsx.hbase/wiki/How-to-use-the-parameter-tableNameAttribute-in-streamsx.hbase-toolkit
