### ISSUE TITLE
Improvement of HBASEPut operator to set the timestamp from a  HBASEPut operator

### ISSUE THREAD

**Issue by anouri** [IBMStreams/streamsx.hbase#114]
Improvement of HBASEPut operator to set the timestamp from a  HBASEPut operator .

The hbase shall has possibility to put a cell into a hbase table with value and timestamp as version.

Put a cell 'value' at specified table/row/column and optionally timestamp coordinates. 
hbase> put 't1', 'r1', 'c1', 'value', ts1 
The customer has requested to improve the HBASEPut operator to set the timestamp from a  HBASEPut operator.

**Comment by jtoso00** [comment]
Hello Ahmad,

Thank you for creating this enhancement request.  I passed along your feedback showing the samples and the customer had the following question.

---
a natural (single element) or composite (two or more elements) hbase key is written for incoming HL7 messages.
a message with the same key is provided, a supplied "epoch" time which is used to keep time sequencing of the versions.
I've looked at the samples and i'm not sure were the puthbase operator allows 'timestamp' value passed.
---

**Comment by anouri** [comment]
2 new parameters have been added to the **HBASEPut** operator:
**Timestamp** and **TimestampAttrName**
The correction will be delivered with the next fix release (streamsx.hbase version 3.7.0)

**Comment by anouri** [comment]
Correction delivered in:
https://github.com/IBMStreams/streamsx.hbase/releases/tag/v3.7.0

**Comment by jtoso00** [comment]
Mayo confirmed these new parameters resolved their request and the case is now closed.  Thank you for delivering this for them.

**Comment by anouri** [comment]
The streamsx.hbase v3.7.0 has been officially delivered in is in the Fix Central:   4.3.1.0-StreamsToolkits-elX-x86_64-i20190808 
https://www-945.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EInformation%20Management&product=ibm/Information+Management/IBM+Streams+Toolkits&release=4.3.0.0&platform=All&function=all
