### ISSUE TITLE
Issues on Toolkit github page

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.hbase#129]
-  [ ] Toolkit still has page referencing bluemix branch: https://ibmstreams.github.io/streamsx.hbase/docs/bluemix/overview/, but the way to connect to IBM Cloud has changed.
-  [ ]  It would be good if the user documentation had some code samples, it only links to SPLDoc for now.  
- [ ]  Samples page just links to the SPLDoc for samples, but these pages do not have any information about the sample itself.
-  [ ] Overview - usecase link is broken on this page: https://ibmstreams.github.io/streamsx.hbase/docs/knowledge/overview/

**Comment by anouri** [comment]
SPLDOC upgraded
SPLDOC for following samples upgraded:
- GetRecord  
- GetSample  
- PutRecord  
- PutSample
-

**Comment by anouri** [comment]
Correction delivered in streamsx.hbase version 3.8.5
https://github.com/IBMStreams/streamsx.hbase/releases/tag/v3.8.5
