### ISSUE TITLE
vulnerability (177835) in Apache commons codec 

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.hbase#132]
apache-commons-codec-info-disc (177835)
https://cert.civis.net/en/index.php?action=alert&param=CCN-177835

Upgrade to the latest version of Commons Codec (1.13-RC1 or later)

**Comment by anouri** [comment]
HBASE: 
Vulnerability issue for 3rh party library commons-codec version 1.12 fixed.
The pom.xml has been adapted to use the commons-codec version 1.14

**Comment by anouri** [comment]
All JUNIT HBASE tests have been passed successfully.
Ready for release.

**Comment by anouri** [comment]
Correction delivered in streamsx.hbase version 3.8.5
https://github.com/IBMStreams/streamsx.hbase/releases/tag/v3.8.5
