### ISSUE TITLE
Vulnerable version of guava in release v3.9.1

### ISSUE THREAD

**Issue by ZollnaPa** [IBMStreams/streamsx.hbase#139]
Here is where I found the vulnerable version of guava: com.ibm.streamsx.hbase/opt/downloaded/guava-20.0.jar. The resolution says: Upgrade to version 24.1.1-jre, 24.1.1-android

**Comment by anouri** [comment]
3rd party library guava upgraded to version 24.1.1-jre.
pom.xml, info.xmal, CHANGELOG.md, HBASEScan.java upgraded.

**Comment by anouri** [comment]
correction delivered in:
https://github.com/IBMStreams/streamsx.hbase/releases/tag/v3.9.2
