### ISSUE TITLE
Deprecate "*AttrName" parameters in favor of "Attr" parameters of type attribute.

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/streamsx.hbase#52]
With Streams 3.2.2Beta, we can now support java operator parameters of type attribute on input streams instead of using Strings we interpret as attributes.   We can do this in a backwards-compatible way, eg, allowing either "columnFamilyAttrName" or "columnFamilyAttr."

This change would affect: 
- columnFamilyAttrName, columnQualifierAttrName, and rowAttrName (HBASEGet, HBASEPut, and HBASEDelete)
- checkAttrName (HBASEPut, HBASEGet)
- incrementAttrName. (HBASEIncrement)

**Comment by hildrum** [comment]
This won't be done for Streams3.2.2, but I hope to do it soon.

**Comment by anouri** [comment]
corrected
