### ISSUE TITLE
Makefile for samples need to work in both product and open-source

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.hbase#65]
Problem reported from Inet, but still valid here:

The Makefiles in $STREAMS_INSTALL/samples/com.ibm.streamsx.inet/HTTPStreamRead as well as the InetSource and InetSourceDynamicURL samples all use this definition to specify the location of the toolkit:

STREAMS_INET_TOOLKIT ?=../../com.ibm.streamsx.inet

However, the relative path to the toolkit from those directories is actually this:
../../../toolkits/com.ibm.streamsx.inet

So, "make" fails with the toolkit not being found.

toolkit path should be set to:
STREAMS_INET_TOOLKIT ?=../../com.ibm.streamsx.inet:${STREAMS_INSTALL}/toolkits/com.ibm.streamsx.inet

**Comment by chanskw** [comment]
Marking as must-fix so we can find later.. not really a must-fix for product.

**Comment by chanskw** [comment]
To be fixed at next possible chance.

**Comment by hildrum** [comment]
I pushed a fix (affecting only the samples in the samples directory, not the extra samples or the test apps) to the toolkitlocation branch
