### ISSUE TITLE
Committer Nomination:  natashadsilva Natasha D'Silva

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.hbase#73]
I would like to nominate Natasha D'Silva to be a committer on the streamsx.hbase project.
Natasha has worked on the Bluemix support for Hbase and contributed to an Alpha release supporting HBase for this toolkit.

**Comment by ddebrunner** [comment]
+1

**Comment by mikespicer** [comment]
+1

**Comment by chanskw** [comment]
Thanks... Welcome @natashadsilva!  Added you as committer to repository.
