### ISSUE TITLE
Hbase Put - Performance improvements

### ISSUE THREAD

**Issue by claudiofusi** [IBMStreams/streamsx.hbase#80]
To improve the performance of the Put operation with 0.9X Hbase client API level :
- consider disabling autoFlush(refer to http://hbase.apache.org/0.94/book/perf.writing.html)
- move the HTable creation to the initialization phase of the operator, instead of creating/closing the HTable for every tuple/batchSize

**Comment by natashadsilva** [comment]
Closing since we have added the `enableBuffer `parameter to disable autoflush if needed.
