### ISSUE TITLE
Upgrade the operator to use new HBASE client API

### ISSUE THREAD

**Issue by claudiofusi** [IBMStreams/streamsx.hbase#81]
The new HBASE client API improve the overall performance.

As for the Put and Delete mutations, the new API doesn't allow setting autoFlush to false for the Table object. To achieve the same effect as the deprecated API, use BufferedMutator.
Moreover using the BufferedMutator provides an efficient buffering mechanism and makes useless implementing the ad hoc ArrayList (see batchSize parameter).

**Comment by natashadsilva** [comment]
@claudiofusi  Are you working on a patch for this as well?

**Comment by anouri** [comment]
The HBASE toolkit has been adapted in V3.1.0 with new HBASE client API.
