### ISSUE TITLE
 How to access hbase with kerberos certification?

### ISSUE THREAD

**Issue by grayworm** [IBMStreams/streamsx.hbase#92]
My environment is Streams 4.2.1.
 I did not see where the hbase toolkit set principal and keytab.
please help.
thanks.
@natashadsilva

**Comment by grayworm** [comment]
I modified HBASEOperator and added Kerberos options. The problem has been solved.

**Comment by natashadsilva** [comment]
@grayworm I am glad you have been able to solve your problem. Sorry about the delay. Do you mean you added Kerberos support to the HBase toolkit? If so, would you be willing to contribute your enhancements?

**Comment by rbs4ba** [comment]
@grayworm I am also interested in seeing Kerberos support added to this toolkit. Would you be willing to contribute your changes back to the repo?
