### ISSUE TITLE
Support for Kerberos KeyTab and Principal Parameters

### ISSUE THREAD

**Issue by rbs4ba** [IBMStreams/streamsx.hbase#94]
Similar to other operators (like the HDFS toolkit operators), it would be helpful to have Kerberos support in the form of operator-parameters: authKeytab & authPrincipal.

I saw another issue #92 that has been closed by the submitter, asking about Kerberos support. It seems like this would be beneficial to many.

**Comment by joergboe** [comment]
We accept this issue as toolkit enhancement.

**Comment by joergboe** [comment]
If you have something, that you can contribute, feel free to open a pull request:
https://github.com/IBMStreams/administration/wiki/Contributing-to-IBMStreams

**Comment by anouri** [comment]
All streamsx.hbase operators have now 2 additional parameters:
**authPrincipal** : This  parameter specifies the Kerberos principal.
**authKeytab**   : This parameter specifies the keytab file that is created for the principal.

**Comment by anouri** [comment]
The corrections for kerberos support have been delivered in kerberos branch.
https://github.com/IBMStreams/streamsx.hbase/tree/kerberos
The tests are in progress.
A how to documentation to setup a kerberos for HABSE is in progress.

**Comment by anouri** [comment]
The correction has been delivered in:
https://github.com/IBMStreams/streamsx.hbase/releases/tag/v3.1.0
