### ISSUE TITLE
HbasePut have not an output on the insert success or error

### ISSUE THREAD

**Issue by giuseppepastore88** [IBMStreams/streamsx.hbase#99]
We read about the parameter "successAttr" but the problem is that this attribute requires another attribute called "checkAttrName". 
In this attribute you define the condition to be checked defining a "ColumnQualifier" and a "ColumnFamily" to the value to insert. Our problem on that approach are:
- The check is done on the quality of the record to insert and not on the result of the insert  in HBASE operation which is exactly what we required
- We want to insert a record with many values with the same columnFamily but different columnQualifier, so we don't know how to pass this mandatory attribute to the "checkAttrName"

**Comment by anouri** [comment]
HbasePut have the parameter "successAttr" , but  it requires the parametr "checkAttrName".
We will check it to improve the HbasePut  operator to support a success parameter underpinning to the "checkAttrName" parameter.

**Comment by jtoso00** [comment]
Hello @anouri, 

Is there a workaound that could be used for the time being that you might be able to suggest?

Thank You,
Jason Toso

**Comment by anouri** [comment]
Correction delivered in V3.3.0
https://github.com/IBMStreams/streamsx.hbase/releases/tag/v3.3.0
